{#
Custom head.
#}
<script type="text/javascript">
  var host = "www.xeworld.com";
  if (("www.xeworld.com" == window.location.host) || ("williamjoe.github.io" == window.location.host))
	  window.location.host = "xeworld.com";
</script>
<meta name="apple-mobile-web-app-capable" content="yes" />   
<meta name="apple-mobile-web-app-status-bar-style" content=black" /> 
<link rel="apple-touch-icon" sizes="57x57" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-57x57.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="60x60" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-60x60.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="72x72" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-72x72.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="76x76" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-76x76.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="114x114" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-114x114.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="120x120" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-120x120.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="144x144" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-144x144.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="152x152" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-152x152.png?v=gAAmLMYXpw">
<link rel="apple-touch-icon" sizes="180x180" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/apple/apple-touch-icon-180x180.png?v=gAAmLMYXpw">
<link rel="icon" type="image/png" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/favicon/favicon-32x32.png?v=gAAmLMYXpw" sizes="32x32">
<link rel="icon" type="image/png" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/favicon/favicon-194x194.png?v=gAAmLMYXpw" sizes="194x194">
<link rel="icon" type="image/png" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/favicon/favicon-96x96.png?v=gAAmLMYXpw" sizes="96x96">
<link rel="icon" type="image/png" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/android/android-chrome-192x192.png?v=gAAmLMYXpw" sizes="192x192">
<link rel="icon" type="image/png" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/favicon/favicon-16x16.png?v=gAAmLMYXpw" sizes="16x16">
<link rel="manifest" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/android/manifest.json?v=gAAmLMYXpw">
<link rel="mask-icon" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/safari/safari-pinned-tab.svg?v=gAAmLMYXpw" color="#56817a">
<link rel="shortcut icon" href="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/favicon/favicon.ico?v=gAAmLMYXpw">
<meta name="msapplication-TileImage" content="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/microsoft/mstile-144x144.png?v=gAAmLMYXpw">
<meta name="msapplication-config" content="https://lawoftech.oss-cn-shanghai.aliyuncs.com/xeworld/icons/microsoft/browserconfig.xml?v=gAAmLMYXpw">